=== Liaoliaoliaole/LOG_CORE/configuration/Morfeas.dtd
<!-- Morfeas_Config.xml -->
	<!-- Components Attributes lists -->
<!ATTLIST OPC_UA_SERVER Disable CDATA #FIXED "false">
<!ATTLIST SDAQ_HANDLER Disable CDATA "false">
<!ATTLIST MDAQ_HANDLER Disable CDATA "false">
<!ATTLIST IOBOX_HANDLER Disable CDATA "false">
<!ATTLIST MTI_HANDLER Disable CDATA "false">
<!ATTLIST NOX_HANDLER Disable CDATA "false">
	<!-- Root and main nodes -->
<!ELEMENT CONFIG (CONFIGS_DIR,LOGGERS_DIR,LOGSTAT_DIR,COMPONENTS)>
<!ELEMENT CONFIGS_DIR (#PCDATA)>
<!ELEMENT LOGGERS_DIR (#PCDATA)>
<!ELEMENT LOGSTAT_DIR (#PCDATA)>
<!ELEMENT CANBUS_IF (#PCDATA)>
<!ELEMENT I2CBUS_NUM (#PCDATA)>
<!ELEMENT IPv4_ADDR (#PCDATA)>
<!ELEMENT DEV_NAME (#PCDATA)>
<!ELEMENT COMPONENTS (OPC_UA_SERVER,SDAQ_HANDLER*,MDAQ_HANDLER*,IOBOX_HANDLER*,MTI_HANDLER*,NOX_HANDLER*)>
	<!-- "OPC_UA_SERVER" node -->
<!ELEMENT OPC_UA_SERVER (APP_NAME)>
<!ELEMENT APP_NAME (#PCDATA)>
	<!-- Handler type nodes -->
<!ELEMENT SDAQ_HANDLER (CANBUS_IF,I2CBUS_NUM?)>
<!ELEMENT MDAQ_HANDLER (DEV_NAME,IPv4_ADDR)>
<!ELEMENT IOBOX_HANDLER (DEV_NAME,IPv4_ADDR)>
<!ELEMENT MTI_HANDLER (DEV_NAME,IPv4_ADDR)>
<!ELEMENT NOX_HANDLER (CANBUS_IF,I2CBUS_NUM?)>

<!-- Morfeas_OPC-UA_Config.xml -->
<!ELEMENT NODESet (CHANNEL*)>
<!ELEMENT CHANNEL (ISO_CHANNEL,
                   INTERFACE_TYPE,
                   ANCHOR,
                   DESCRIPTION,
                   MIN,
                   MAX,
                   UNIT?,
                   CAL_DATE?,
                   CAL_PERIOD?,
                   BUILD_DATE?,
                   MOD_DATE?,
                   ALARM_HIGH_VAL?,
                   ALARM_LOW_VAL?,
                   ALARM_HIGH?,
                   ALARM_LOW?)>
<!ELEMENT ISO_CHANNEL (#PCDATA)>
<!ELEMENT INTERFACE_TYPE (#PCDATA)>
<!ELEMENT ANCHOR (#PCDATA)>
<!ELEMENT DESCRIPTION (#PCDATA)>
<!ELEMENT MIN (#PCDATA)>
<!ELEMENT MAX (#PCDATA)>
<!ELEMENT UNIT (#PCDATA)>
<!ELEMENT CAL_DATE (#PCDATA)>
<!ELEMENT CAL_PERIOD (#PCDATA)>
<!ELEMENT BUILD_DATE (#PCDATA)>
<!ELEMENT MOD_DATE (#PCDATA)>
<!ELEMENT ALARM_HIGH_VAL (#PCDATA)>
<!ELEMENT ALARM_LOW_VAL (#PCDATA)>
<!ELEMENT ALARM_HIGH (#PCDATA)>
<!ELEMENT ALARM_LOW (#PCDATA)>

=== Liaoliaoliaole/LOG_CORE/configuration/Morfeas_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CONFIG SYSTEM "Morfeas.dtd">
<CONFIG>
	<!--<CONFIGS_DIR>/home/pi/Morfeas_proj/Morfeas_core/configuration</CONFIGS_DIR>-->
	<CONFIGS_DIR>/home/pi/Morfeas_proj/Morfeas_core/configuration</CONFIGS_DIR>
	<LOGGERS_DIR>/mnt/ramdisk/Morfeas_Loggers/</LOGGERS_DIR>
	<LOGSTAT_DIR>/mnt/ramdisk/</LOGSTAT_DIR>
	<COMPONENTS>
		<OPC_UA_SERVER>
			<APP_NAME>Morfeas_test(Proto)</APP_NAME>
		</OPC_UA_SERVER>
		<SDAQ_HANDLER Disable="false">
			<CANBUS_IF>can0</CANBUS_IF>
		</SDAQ_HANDLER>
		<SDAQ_HANDLER Disable="false">
			<CANBUS_IF>can1</CANBUS_IF>
		</SDAQ_HANDLER>
		<SDAQ_HANDLER Disable="true"> 
			<CANBUS_IF>vcan0</CANBUS_IF>
		</SDAQ_HANDLER>
		<MDAQ_HANDLER Disable="true">
			<DEV_NAME>LAD_MDAQ</DEV_NAME>
			<IPv4_ADDR>10.0.0.10</IPv4_ADDR>
		</MDAQ_HANDLER>
		<IOBOX_HANDLER Disable="true">
			<DEV_NAME>LAD_IOBOX</DEV_NAME>
			<IPv4_ADDR>10.0.0.7</IPv4_ADDR>
		</IOBOX_HANDLER>
		<MTI_HANDLER Disable="true">
			<DEV_NAME>test3</DEV_NAME>
			<IPv4_ADDR>10.0.0.11</IPv4_ADDR>
		</MTI_HANDLER>
		<NOX_HANDLER Disable="true">
			<CANBUS_IF>can1</CANBUS_IF>
		</NOX_HANDLER>
	</COMPONENTS>
</CONFIG>

=== Liaoliaoliaole/LOG_CORE/configuration/OPC_UA_Config.xml
<?xml version="1.0" ?>
<!DOCTYPE NODESet
  SYSTEM 'Morfeas.dtd'>
<NODESet>
        <CHANNEL>
                <ISO_CHANNEL>TE1</ISO_CHANNEL>
                <INTERFACE_TYPE>SDAQ</INTERFACE_TYPE>
                <ANCHOR>1.CH1</ANCHOR>
                <DESCRIPTION>This is a test 1</DESCRIPTION>
                <MIN>0</MIN>
                <MAX>200</MAX>
        </CHANNEL>
        <CHANNEL>
                <ISO_CHANNEL>TE2</ISO_CHANNEL>
                <INTERFACE_TYPE>SDAQ</INTERFACE_TYPE>
                <ANCHOR>2.CH01</ANCHOR>
                <DESCRIPTION>This is a test 2</DESCRIPTION>
                <MIN>-100.55</MIN>
                <MAX>300</MAX>
        </CHANNEL>
        <CHANNEL>
                <ISO_CHANNEL>TE3</ISO_CHANNEL>
                <INTERFACE_TYPE>SDAQ</INTERFACE_TYPE>
                <ANCHOR>3.CH1</ANCHOR>
                <DESCRIPTION>This is a test 3</DESCRIPTION>
                <MIN>0</MIN>
                <MAX>500</MAX>
        </CHANNEL>
        <CHANNEL>
                <ISO_CHANNEL>TE4</ISO_CHANNEL>
                <INTERFACE_TYPE>SDAQ</INTERFACE_TYPE>
                <ANCHOR>4.CH1</ANCHOR>
                <DESCRIPTION>This is a test 4</DESCRIPTION>
                <MIN>0</MIN>
                <MAX>500</MAX>
        </CHANNEL>
        <CHANNEL>
                <ISO_CHANNEL>TE567</ISO_CHANNEL>
                <INTERFACE_TYPE>SDAQ</INTERFACE_TYPE>
                <ANCHOR>626191848.CH1</ANCHOR>
                <DESCRIPTION>Test ISO channel for S/N:626191848</DESCRIPTION>
                <MIN>0</MIN>
                <MAX>500</MAX>
        </CHANNEL>
        <CHANNEL>
                <ISO_CHANNEL>TE89a</ISO_CHANNEL>
                <INTERFACE_TYPE>SDAQ</INTERFACE_TYPE>
                <ANCHOR>624642519.CH5</ANCHOR>
                <DESCRIPTION>Test ISO channel for S/N:624642519</DESCRIPTION>
                <MIN>0</MIN>
                <MAX>500</MAX>
        </CHANNEL>
        <CHANNEL>
                <ISO_CHANNEL>TE100_RX</ISO_CHANNEL>
                <INTERFACE_TYPE>IOBOX</INTERFACE_TYPE>
                <ANCHOR>117440522.RX1.CH1</ANCHOR>
                <DESCRIPTION>Test ISO channel for IOBOX</DESCRIPTION>
                <MIN>-40</MIN>
                <MAX>1500</MAX>
                <UNIT>°C</UNIT>
        </CHANNEL>
        <CHANNEL>
                <ISO_CHANNEL>TE200</ISO_CHANNEL>
                <INTERFACE_TYPE>MDAQ</INTERFACE_TYPE>
                <ANCHOR>167772170.CH1.Val1</ANCHOR>
                <DESCRIPTION>Test ISO channel for MDAQ</DESCRIPTION>
                <MIN>-2.5</MIN>
                <MAX>2.5</MAX>
                <UNIT>°C</UNIT>
        </CHANNEL>
<!---->
</NODESet>
